kind: Template
apiVersion: v1
metadata:
  name: moon
objects:

  - kind: ResourceQuota
    apiVersion: v1
    metadata:
      name: max-moon-sessions
    spec:
      hard:
        pods: ${MOON_PODS}

  - kind: Service
    apiVersion: v1
    metadata:
      name: moon
    spec:
      selector:
        app: moon
      ports:
      - name: moon
        protocol: TCP
        port: 4444
      type: NodePort

  - kind: Service
    apiVersion: v1
    metadata:
      name: moon-api
    spec:
      selector:
        app: moon-api
      ports:
      - name: moon-api
        protocol: TCP
        port: 8080
      type: NodePort

  - kind: Service
    apiVersion: v1
    metadata:
      name: moon-ui
    spec:
      selector:
        app: moon-ui
      ports:
      - name: moon-ui
        protocol: TCP
        port: 8080
      type: NodePort

  - kind: DeploymentConfig
    apiVersion: v1 
    metadata:
      name: moon
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: moon
        spec:
          containers:
          - name: moon
            image: ${MOON_IMAGE}
            args:
              - '-namespace'
              - '${NAMESPACE}'
            resources:
              limits:
                cpu: "1"
                memory: "512Mi"
              requests:
                cpu: "0.25"
                memory: "64Mi"
            ports:
            - containerPort: 4444
            volumeMounts:
            - name: quota
              mountPath: /quota
              readOnly: true
            - name: users
              mountPath: /users
              readOnly: true
          volumes:
          - name: quota
            configMap:
              name: quota
          - name: users
            secret:
              secretName: users

  - kind: DeploymentConfig
    apiVersion: v1 
    metadata:
      name: moon-api
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: moon-api
        spec:
          containers:
          - name: moon-api
            image: ${MOON_API_IMAGE}
            args:
              - '-namespace'
              - '${NAMESPACE}'
            resources:
              limits:
                cpu: "0.25"
                memory: "128Mi"
              requests:
                cpu: "0.1"
                memory: "64Mi"        
            ports:
            - containerPort: 8080
            volumeMounts:
            - name: quota
              mountPath: /quota
          volumes:
          - name: quota
            configMap:
              name: quota
          - name: users
            secret:
              secretName: users

  - kind: DeploymentConfig
    apiVersion: v1 
    metadata:
      name: moon-ui
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: moon-ui
        spec:
          containers:
            - name: moon-ui
              args:
                - '--selenoid-uri'
                - 'http://moon-api:8080'
              image: ${MOON_UI_IMAGE}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: 100m
                  memory: 64M

parameters:
- name: NAMESPACE
  displayName: Namespace
  description: Namespace where the Moon is running
  value: default
  required: true

- name: MOON_IMAGE
  displayName: Moon docker image
  description: Name of the image to be used.
  value: aerokube/moon:latest-release
  required: true

- name: MOON_API_IMAGE
  displayName: Moon-API docker image
  description: Name of the image to be used.
  value: aerokube/moon-api:latest-release
  required: true

- name: MOON_UI_IMAGE
  displayName: Moon-UI docker image
  description: Name of the image to be used.
  value: aerokube/selenoid-ui:latest-release
  required: true

- name: MOON_PODS
  displayName: Max moon pods in project
  description: Specify max moon pods for project (4 free slots + Moon + Moon API + Moon UI = 7).
  value: '7'
  required: true